// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA90q71vSr2bxaYzaXnWHISsldfSmFEgVA',
    appId: '1:956449049141:web:dfb84e12135303bd59bf7c',
    messagingSenderId: '956449049141',
    projectId: 'flutterfireauthen',
    authDomain: 'flutterfireauthen.firebaseapp.com',
    storageBucket: 'flutterfireauthen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6kMcEbYHxoSgORlSet-iK0uw9CG9gBJU',
    appId: '1:956449049141:android:3d0c09f299241caa59bf7c',
    messagingSenderId: '956449049141',
    projectId: 'flutterfireauthen',
    storageBucket: 'flutterfireauthen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQZMay4UtdWxWhOmizCCId37nTfN_DeU',
    appId: '1:956449049141:ios:8d1510b0f122019b59bf7c',
    messagingSenderId: '956449049141',
    projectId: 'flutterfireauthen',
    storageBucket: 'flutterfireauthen.appspot.com',
    iosBundleId: 'com.example.flutterfireAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFQZMay4UtdWxWhOmizCCId37nTfN_DeU',
    appId: '1:956449049141:ios:59d2a62ef9c144f359bf7c',
    messagingSenderId: '956449049141',
    projectId: 'flutterfireauthen',
    storageBucket: 'flutterfireauthen.appspot.com',
    iosBundleId: 'com.example.flutterfireAuthen.RunnerTests',
  );
}
